//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SawYouWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SawYouEntry
    {
        public int Id { get; set; }
        public Nullable<short> CheckInType { get; set; }
        public string FoursquareVenueId { get; set; }
        public string FoursquareVenueName { get; set; }
        public string FoursquareVenueAddress { get; set; }
        public string Email { get; set; }
        public string CheckInDescription { get; set; }
    }
}
